// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csfvsbiivitndafwabqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzZnZzYmlpdml0bmRhZndhYnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjkwNzcsImV4cCI6MjA1OTQ0NTA3N30.ZFIM0h5jqcbLW1H-Wwa_Vp6eCXR0LPSkzOfoMRh5p_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);